Тесты для моделей задач
EvgeniMeleshin/ToDoListCleanSwift pull request #10
Opened 2023-03-11 05:59 UTC by EvgeniMeleshin

Добавлены тесты для RegularTask, ImportantTask. Также enum ImportantTaskPriorities подписан под CaseIterable, для реализации теста completionDate

2023-03-11 08:16 UTC, Blissfulman requested changes

2023-03-11 08:16 UTC, Blissfulman commented on Tests/TestsTasksModels.swift
> +enum TasksStub {
Если не требуется в других файлах, стоит сделать приватным

2023-03-11 08:16 UTC, Blissfulman commented on Tests/TestsTasksModels.swift
> +			guard let sut = TasksStub.importantTaskByRawValue(rawValue: priority.rawValue) else { return }
Для чего здесь ты сначала получаешь количество дней по приоритету, а потом внутри функции обратно по количеству дней инициализируешь приоритет. Можно же передать в функцию сразу приоритет.

А также, при уходе в блок `else`, тест всегда успешный, даже есть проверок никаких не производилось. То есть возможен случай, когда тест не будет ничего проверять, но будет сигнализировать, что всё успешно.

2023-03-11 08:16 UTC, Blissfulman commented on Tests/TestsTasksModels.swift
> +	static var importantTaskLow = ImportantTask(title: "Important task low", priority: .low)
Эти свойства нигде не используются

2023-03-11 08:20 UTC, Blissfulman commented on Tests/TestsTasksModels.swift
> +			guard let sut = TasksStub.importantTaskByRawValue(rawValue: priority.rawValue) else { return }
На самом деле и функция избыточно. достаточно на 56 строке просто создать задачу:
`let sut = ImportantTask(title: "Important task example", priority: priority)`

2023-03-11 09:18 UTC, Blissfulman commented on Tests/TestsTasksModels.swift
> +	/// Тест: после вызова метода значение должно быть инвертировано
Здесь больше подходят обычные комменты, а не документирующие, т.к. этот метод больше нигде не вызывается и док. коммент не несёт никакой пользы. Само слово "Тест" можно опустить и просто описать суть того, что проверяется.

2023-03-11 10:19 UTC, EvgeniMeleshin commented on Tests/TestsTasksModels.swift
> +	}
Fixed

2023-03-11 10:19 UTC, EvgeniMeleshin commented on Tests/TestsTasksModels.swift
> +    }
Fixed

2023-03-11 10:20 UTC, EvgeniMeleshin commented on Tests/TestsTasksModels.swift
> +final class TestImportantTask: XCTestCase {
Разделил на 2 файла

2023-03-11 10:20 UTC, EvgeniMeleshin commented on Tests/TestsTasksModels.swift
> +	}
Изменил логику проверки

2023-03-11 10:21 UTC, EvgeniMeleshin commented on Tests/TestsTasksModels.swift
> +enum TasksStub {
Отказался полностью

2023-03-11 10:22 UTC, EvgeniMeleshin commented on Tests/TestsTasksModels.swift
> +			guard let sut = TasksStub.importantTaskByRawValue(rawValue: priority.rawValue) else { return }
Изменил логику с rawValue на dayCountForCompletion, ну и весь наш маленький стаб теперь на ходу делается

2023-03-11 10:22 UTC, EvgeniMeleshin commented on Tests/TestsTasksModels.swift
> +	static var importantTaskLow = ImportantTask(title: "Important task low", priority: .low)
Fixed

2023-03-11 10:23 UTC, EvgeniMeleshin commented on Tests/TestsTasksModels.swift
> +	/// Тест: после вызова метода значение должно быть инвертировано
Fixed

2023-03-11 19:14 UTC, Blissfulman approved these changes

2023-03-12 02:07 UTC, leilatl approved these changes

2023-03-12 08:04 UTC, SShliakhin approved these changes

2023-03-12 09:40 UTC, merged